apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: limiteddeployments.apps.tharun.com
spec:
  group: apps.tharun.com
  scope: Namespaced
  names:
    kind: LimitedDeployment
    plural: limiteddeployments
    singular: limiteddeployment
    shortNames:
      - ldep
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - replicas
                - image
              properties:
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 10
                image:
                  type: string
                port:
                  type: integer
                  minimum: 1
                  maximum: 65535
