apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: csi-account-role
rules:
- apiGroups: ["secrets-store.csi.k8s.io"]
  resources: ["secretproviderclasses"]
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: csi-account-rolebinding
subjects:
- kind: ServiceAccount
  name: csi-account
roleRef:
  kind: Role
  name: csi-account-role
  apiGroup: rbac.authorization.k8s.io