# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: aws-test-secret-provider
# spec:
#   provider: aws
#   parameters:
#     objects: |
#       - objectName: "db-creds"
#         objectType: "secretsmanager"

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-test-secret-provider
  namespace: two
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: db-creds
        objectType: secretsmanager
        jmesPath:
          - path: username
            objectAlias: myusername
          - path: pass
            objectAlias: mypassword
  secretObjects:
  - secretName: test-secret
    type: Opaque
    data:
    - objectName: myusername
      key: k8s-myusername
    - objectName: mypassword
      key: k8s-mypassword
