apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  labels:
    app: nginx
spec:
  rule:
    -  host: icone.com
       http:
        paths:
          - pathtype: prefix
            path: "/icone"
            backend:
              service: 
                name: test
                port:
                  number: 80
