# Here we are creating the custom crd for pupolator and make sure install volume populator

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: generichttppopulators.stable.example.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: k8s.tharun.dev 
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                uri:
                  type: string

  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: generichttppopulators
    # singular name to be used as an alias on the CLI and for display
    singular: generichttppopulator
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: GenericHTTPPopulator
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - ghp

---
# now we need to fetch the uri to the volume populator and add to the pvc

apiVersion: k8s.tharun.dev/v1
kind: GenericHTTPPopulator
metadata:
  name: readmefile
spec:
  uri: https://raw.githubusercontent.com/THARUN13055/quick_install_linux/main/README.md
---

apiVersion: v1
kind: PersistentVolumeClime
metadata:
  name: mypvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  dataSourceRef:
    apiGroup: k8s.tharun.dev
    name: readmefile
    kind: GenericHTTPPopulator

