apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-python
  template:
    metadata:
      labels:
        app: my-python
    spec:
      containers:
      - name: py-container
        image: tharun13055/python:latest
        resources:
        ports:
        - containerPort: 80


--- 

apiVersion: v1
kind: Service
metadata:
  name: my-python
spec:
  selector:
    app: my-python
  ports:
  - port: 80
    targetPort: 80
    protocal: TCP




