apiVersion: rbac.authorization.k8s.io/v1
kind: Roles
metadata: 
  name: node-role
  namesapce: project
rules:
  - apiGroup: [""]
    resources: ["node"]
    verbs: ["gets","watch","delete","list","create","upgrade"]
    