apiVersion: rbac.authorization.k8s.io/v1
kind: Roles
metadata:
  name: pod-roles
  namespace: project
rules:
  - apiGroup: [""]
    resources: ["Pods"]
    verbs: ["gets","watch","delete","list","create","upgrade"]