apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment-name}}
  {{- if .Values.namespace}}
  namespace: {{ .Values.namespace}}
  {{- end}}
  labels:
    {{- include .Values.labels | indent 4}}
spec:
  replicas: {{ .Values.replicasCount }}
  selector:
    matchLables:
      {{- include .Values.labels | indent 6}}
  templates:
    metadata:
      labels:
      {{- include .Values.labels | indent 8}}
    spec:
      containers:
        - name: {{ .Values.image.containername }}
          image: {{ .Values.image.images}}
          ports:
            - name: {{ .Values.containerPort.name}}
              containerPort: {{ .Values.containerPort.cport}}
          
