replicaCount: 2

deployment-name: nginx-deployment
service-name: nginx-service

labels:
  app: nginx

image:
  containername: my-container-nginx
  images: nginx:latest


containerPort:
  name: web
  cport: 80

namespace: nginx

services:
  nodePort: 8080
  targetPort: 80
  type : NodePort
