apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tharun-namespace-reader-binding
subjects:
- kind: User
  name: tharun
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: tharun-namespace-reader
  apiGroup: rbac.authorization.k8s.io
